# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3      
    - name: Install tools from asdf config
      uses: ai/asdf-cache-action@v1
    - name: Install dependencies
      uses: Gr1N/setup-poetry@v8
    - run: poetry install
    - name: Lint with mypy and flake8
      run: poetry run lint
    - name: Test with pytest
      run: poetry run pytest
