# This workflow will upload a Python Package to PyPI when a release is created.

name: Upload Python Package

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gather runtime environment versions - asdf
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
